### ISSUE TITLE
UTC timezone

### ISSUE THREAD

**Issue by ghost** [ezbz/graphitus#10]
This is more of a question than an issue, but I'm trying to set up a dashboard to be displayed in UTC time, but have been unable to make it work. What would the correct setting for "tz": should be to get UTC time?

Thanks!

**Comment by nb71** [comment]
You should edit dashboard.html and after the last option (Europe/London) you can add
GMT or
UCT or
Zulu or
Universal.

All are the same

**Comment by ezbz** [comment]
This was moved to config.json to allow setting timezones more easily
