### ISSUE TITLE
Add possibility to include ${} parameters in graph title and description (both on page and permalink images)

### ISSUE THREAD

**Issue by blufor** [ezbz/graphitus#11]
I believe, the title speaks for itself :] It'd be awesome especially when you want to send the permalink to someone so he/she could actually see the context of graphed entity (ie. hostname)

**Comment by johntdyer** [comment]
Would also be great to support this in the parameters node as well, eg &colorList=${colors}

``` json
            "Staging": {
                "grouping": "{203,204}",
                "colors" : "blue,blue"
            },
```

And then use the replacement in the dashboard as well

``` json
   "target" : [
        "aliasSub(aliasByNode(server${grouping}.collectd.curl_json-PrismApplicationServer.frequency-value-SessionCPS,0),'^(tropo\\d{3})_.*','\\1 CPS')"
        ],
        "params" : "yUnitSystem=none&areaMode=stacked&colorList=${colors}"
      }
```

**Comment by ezbz** [comment]
This was solved by https://github.com/erezmazor/graphitus/commit/39abc60ae015580618a25942697827bfc2e8433d and https://github.com/erezmazor/graphitus/commit/6f711663f341aab8170af7189efa56104b01ab40
