### ISSUE TITLE
Limiting the amount of results

### ISSUE THREAD

**Issue by ghost** [ezbz/graphitus#12]
When using ".*" as target it would be nice to be able to limit the amount of results to, say, top 10 (by highest value or something). Is there a way to do this currently?

**Comment by ezbz** [comment]
Wrap you target with graphite `limit` function:

limit(requestContext, seriesList, n)

See: http://graphite.readthedocs.org/en/1.0/functions.html for documentation

**Comment by ghost** [comment]
Awesome! Thanks!
