### ISSUE TITLE
Graphitus only works in IE9 after the developer tools have been opened

### ISSUE THREAD

**Issue by JohnLyman** [ezbz/graphitus#15]
I ran into a bug with IE9 that is discussed here:  http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once

I worked around it by adding the following to dashboard.html and index.html per the stackoverflow link:

``` html
<!-- IE9 fix from http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once -->
<script type="text/javascript">try{ console }catch(e){ console={}; console.log = function(){}; }</script>
```

**Comment by ezbz** [comment]
Great, not up for solving IE bugs here (meh)
