### ISSUE TITLE
Times are wrong and inconsistent in detail graph view

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [ezbz/graphitus#17]
When you click on a graph to get to the detailed view where you can disable metrics and things like that, the time in the x axis is totally off.

Where as my local time is 12:30, the GMT time is 11:30 (which is my configured timezone and also the time in the graph rendered by graphite) the time the x axis displays is 7:30 and even better the mouse over time displayed when you hover over a datapoint is 6:30.

I tried changing my configured timezone to "Europe/Berlin" but that had no effect on the detail view (only the graphite-rendered graphs times changed).

**Comment by damm** [comment]
what Rickshaw gets back should be (before Graphite 0.9.12+) was UTC.  So if you configured &tz=US/Pacific&format=json it would still return UTC.

Not sure if this is relevant or not.

**Comment by mathias-baumann-sociomantic** [comment]
I looked at the actual request and it gets back raw unix timestamps. Internally there is a function called `calculateTimezoneOffset` (see https://github.com/erezmazor/graphitus/blob/master/js/extended-graph.js#L73) which just returns a constant which is substracted from the timestamps returned by graphite. Returning 0 here will make the time GMT/UTC again. In no case it seems to care at all about the actual timezone that is set.
For that to work, I assume that you have to add some internal timezone handling (it is done by graphite for the graphs returned by it, but the detail view gets raw data)

**Comment by ezbz** [comment]
When this was written I didn't find any good timezone library, I have now integrated http://momentjs.com/timezone/ into a local branch and will soon check it in to master. However this will require generating timezone data for all relevant timezones via the data builder (http://momentjs.com/timezone/data/)
