### ISSUE TITLE
Dynamic parameters hidden by top menu bar

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [ezbz/graphitus#21]
If you decrease the browser window width too much, the top bar overlaps with the dynamic parameter drop down menus (in chrome at least).

**Comment by ezbz** [comment]
A fix for this was already attempted, however it doesn't work perfectly

https://github.com/erezmazor/graphitus/commit/7304f2723e975afb2f9a7a45e2cb3e78ff5ee214
