### ISSUE TITLE
renderDynamicParamGroup appends ".*" to the query

### ISSUE THREAD

**Issue by nithril** [ezbz/graphitus#3]
Hello,

If for example query is:

``` json
"service": {
        "type": "dynamic",
        "query": "*",
        "index": 2,
        "showAll": false
    }
```

The query becomes "_._" and return to much results

**Comment by ezbz** [comment]
This was fixed in the private branch I will integrate into master for now you can simply omit the \* suffix from your path and it will be appended

**Comment by nithril** [comment]
Thanks.
