### ISSUE TITLE
minimumRefresh not set causes immediate refreshes

### ISSUE THREAD

**Issue by chrishoffman** [ezbz/graphitus#4]
If the graphitusConfig.minimumRefresh is not set the config.refreshIntervalSeconds becomes undefined causing the updates to happen immediately upon return of the previous update.  There probably should be a default value set for graphitusConfig.minimumRefresh.

**Comment by ezbz** [comment]
Fixed https://github.com/erezmazor/graphitus/commit/c6ba04f4c3877f0dacacf1649ae01f76a3ec14fc
