### ISSUE TITLE
Dashboard generator

### ISSUE THREAD

**Issue by ghost** [ezbz/graphitus#5]
It would be awesome to have an admin interface to create dashboards and not having to manually edit json files, something that roughly works as the graphite browser and generates the files

**Comment by ezbz** [comment]
I have something internal in the works, however this would required specifying the json store to use (e.g., mongo, etc) which I've avoided

**Comment by ghost** [comment]
why not use regular files like it is now?

**Comment by damm** [comment]
You would have to configure webdav to have it push back changes.   Doing this to Mongo or CouchDB is very easy in JS in comparison.

> That is my opinion on why.

**Comment by ghost** [comment]
Thanks for the clarification, I now nothing about JS hence, I fell compelled to ask. It would still be awesome to see the "internal" project come to light, maybe as separate fork or branch if you don't to make the whole project dependable on that, so that we can work on that from there. Thanks for an awesome job!

**Comment by ezbz** [comment]
I am currently in the process of migrating this to angularJS when I'm done I will push all changes as well as the (mongo based) dashboard editor
