### ISSUE TITLE
Targets with same name

### ISSUE THREAD

**Issue by ghost** [ezbz/graphitus#7]
I have targets in graphite that look like this:

stats.something.nice

and

stats.something.nice.r

When I try to see them in a graph, I can only see the second one. The first one seems to be ignored because of being a non-terminal for the other target.

**Comment by ezbz** [comment]
Not sure I understand this use case what you're describing, when viewed in the native graphite browser:

stats.something.nice is a node (folder)
stats.something.nice.r is a metric (leaf)

how do you expect to see stats.something.nice in a target? am I missing something here?

**Comment by ghost** [comment]
The difference is that stats.something.nice is a node or folder for the second metric, but it's also a leaf on it's own. 
To put it simple, both are metrics, it's just that the shorter one also acts as node for the second one. In the graphite browser I can see them both correctly, but Graphitus ignores the first one.

**Comment by ezbz** [comment]
What does the graphite browser show you under "stats.something"? do you have folder call "nice" and then a metric named "nice"? I've never come across this use case before, I can try to simulate, can you send me your graphitus config?

**Comment by ghost** [comment]
In the graphite tree view it would show a folder "stats" and under it there would be two items: a metric called "something" and a folder called "something". The metric would show it's graph and if I clicked the "something" folder I would see that under it there was a "nice" metric.
I can't show you the graphitus config since this happened a long time ago and I have changed the metrics names since, but I was just trying to have them both displayed in one graph, and it would fail to show the metric "something", it would only show the metric "nice". My guess is that it was considering the target incomplete since it was finding a folder with that name as well.
