### ISSUE TITLE
Dashboard Toolbar Doesn't resize correctly

### ISSUE THREAD

**Issue by bdouglasGitHub** [ezbz/graphitus#9]
I wanted to submit this issue that I'm experiencing with the toolbar on each dashboard not resizing correctly.

In reference to the images I uploaded, in the pictures titled small and larger, I'm able to see they toolbar which contains systype > and host > 
However, in the medium and large pictures, the toolbar disappears.
Small
![small](https://f.cloud.github.com/assets/5667200/1363851/834903e4-3833-11e3-8a13-3c714ba3a75d.png)
Medium
![medium](https://f.cloud.github.com/assets/5667200/1363852/845bb4d4-3833-11e3-96e3-bfbc6d463d0a.png)
Large
![large](https://f.cloud.github.com/assets/5667200/1363853/8600b3de-3833-11e3-9172-e6ce90c33eb3.png)
Larger
![larger](https://f.cloud.github.com/assets/5667200/1363854/8746254e-3833-11e3-8ae3-370928000a96.png)

**Comment by ezbz** [comment]
this issue has been reported by other users, common workaround is to use zoom out in the browser and use the unlock button on the parameter toolbar to make it float. I will take a shot at fixing/redesigning this soon.
